name: Shellcheck

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
